# Generated by Django 5.1.1 on 2024-09-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_ram_product_speed_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='WP',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producer',
            new_name='speed',
        ),
    ]
